# Bu dosya, Python betiğinin ayarlarını içerir.
# Sunucu adresi değiştiğinde sadece 'base_url' kısmını güncelleyin ve
# değişiklikleri GitHub'a gönderin (push). Action otomatik olarak çalışacaktır.

# Kanalların çekileceği kaynak M3U listesinin tam adresi.
source_playlist_url: "http://e6173063453a.mylistbest.com/playlists/uplist/0a32c58fac3b6b11d8ab71209ee5e90f/playlist.m3u8"

# Oluşturulacak yeni M3U dosyasının adı.
output_file: "donusturulmus_liste.m3u8"
