import requests
import os

# === AYARLAR ===
url = "https://raw.githubusercontent.com/doGior/doGiorsHadEnough/refs/heads/master/Huhu/src/main/kotlin/it/dogior/hadEnough/Huhu.kt"
output_file = "huhu.m3u"

# === M3U DOSYASINI İNDİR ===
def m3u_indir():
    try:
        headers = {
            "User-Agent": "Mozilla/5.0"
        }
        print("[*] M3U dosyası indiriliyor...")
        r = requests.get(url, headers=headers, timeout=30)
        r.raise_for_status()

        with open(output_file, "w", encoding="utf-8") as f:
            f.write(r.text)

        print(f"[+] M3U dosyası başarıyla indirildi: {output_file}")
        return True
    except requests.exceptions.RequestException as e:
        print(f"[!] Dosya indirilemedi: {e}")
        return False

# === M3U DOSYASINDAN KANAL LİSTESİ ÇIKAR ===
def m3u_listele():
    if not os.path.isfile(output_file):
        print(f"[!] '{output_file}' dosyası bulunamadı.")
        return

    kanallar = []

    with open(output_file, "r", encoding="utf-8") as f:
        satirlar = f.readlines()

    for i in range(len(satirlar)):
        satir = satirlar[i].strip()
        if satir.startswith("#EXTINF"):
            kanal_adi = satir.split(",")[-1]
            if i + 1 < len(satirlar):
                url = satirlar[i + 1].strip()
                kanallar.append((kanal_adi, url))

    if not kanallar:
        print("[!] M3U dosyasında kanal bulunamadı.")
    else:
        print(f"\n[+] Toplam {len(kanallar)} kanal bulundu:\n")
        for index, (kanal, url) in enumerate(kanallar, start=1):
            print(f"{index}. {kanal}")
            print(f"   URL: {url}\n")

# === ANA PROGRAM ===
if __name__ == "__main__":
    if m3u_indir():
        m3u_listele()
