name: Build IPTV M3U Playlist

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests

      - name: Run IPTV script with debug output
        run: |
          python Mac2M3uPlaylist.py > full_output.log 2>&1
          cat full_output.log

      - name: List output directory contents
        run: ls -l output/

      - name: Upload M3U playlist artifact
        uses: actions/upload-artifact@v4
        with:
          name: iptv-playlist
          path: output/Mac2M3uPlaylist.m3u
