name: Multi YouTube Live M3U Recorder

on:
  schedule:
    - cron: "*/30 * * * *"  # Her 30 dakikada bir çalıştır
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  record-live:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu klonla
        uses: actions/checkout@v4

      - name: Python ortamını kur
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Gerekli kütüphaneleri yükle
        run: pip install yt-dlp requests

      - name: Cookie dosyasını oluştur
        run: echo "${{ secrets.YOUTUBE_COOKIES }}" > cookies.txt

      - name: Canlı yayınları kontrol et ve M3U oluştur
        run: python main.py

      - name: M3U dosyalarını sakla
        uses: actions/upload-artifact@v4
        with:
          name: youtube_live_m3u_links
          path: "*.m3u"
