name: Günlük IPTV Güncelleme

on:
  schedule:
    - cron: '0 3 * * *'  # Her gün 03:00 UTC'de çalışacak
  workflow_dispatch:

permissions:
  contents: write

env:
  BASE_URL: "https://goldvod.org/tv/vavoo?id="
  SOURCE_PLAYLIST_URL: "https://raw.githubusercontent.com/troy8865/vwovov/refs/heads/main/vavoo.m3u"
  OUTPUT_FILE: "serby.m3u"

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        run: python script.py

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add ${{ env.OUTPUT_FILE }}
          git commit -m "🔄 Otomatik serby.m3u güncellemesi" || echo "Değişiklik yok"
          git push
