name: Günlük serby.m3u Güncelleme

on:
  schedule:
    - cron: '0 3 * * *'  # Her gün saat 03:00 (UTC)
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Bağımlılıkları yükle
        run: pip install requests

      - name: serby.m3u dosyasını oluştur
        run: python script.py

      - name: Değişiklikleri GitHub'a gönder
        run: |
          git config user.name "GitHub Action"
          git config user.email "action@github.com"
          git add serby.m3u
          git commit -m "🔄 Otomatik serby.m3u güncellemesi" || echo "Değişiklik yok"
          git push
