name: Update Live TV Streams

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */2 * * *' # Her 2 saatte bir çalışır (UTC)

jobs:
  update-streams:
    runs-on: ubuntu-latest

    steps:
      - name: Repoyu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Gerekli paketleri yükle ve ffmpeg kur
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4 pyyaml
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Streamleri güncelle ve kaydet
        run: python ulusal.py

