name: Update TV Streams

on:
  workflow_dispatch:  # Manuel tetikleme
  schedule:
    - cron: "0 */2 * * *"  # Her 2 saatte bir çalıştır

jobs:
  update-streams:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml beautifulsoup4

      - name: Update TV Streams (only links)
        run: |
          python ulusal.py
